language: java
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
    - /^dependabot.*$/
jobs:
  include:
    - stage: test
      jdk: openjdk8
      script:
        - mvn verify
    - stage: test
      jdk: openjdk11
      script:
        - mvn verify
    - stage: test
      jdk: openjdk14
      script:
        - mvn verify
stages:
 - test
